### ISSUE TITLE
Installation impossible sur yunohost v 2.5.6

### ISSUE THREAD

**Issue by ljoets** [YunoHost-Apps/galette_ynh#1]
Bonjour,
Je tente en vain d'installer galette sur mon yunohost à jour (2.5.6).
Via l'interface web, l'installation n'aboutit pas.
En ligne de commande, voici ce que j'obtiens :
root@YunoHost:~# yunohost app install https://github.com/alexAubin/galette_ynh
Choose a domain for galette: home.*****.net
Choose a path for galette (default: /galette): 
Admin login (default: galette_admin): 
Admin password: *****
Is it a public application ? [Yes | No] (default: Yes): 
Warning: ERROR 1008 (HY000) at line 1: Can't drop database 'galette'; database doesn't exist
Error: Installation failed

Est-ce que cette app est supposée pouvoir s'installer sur un yunohost récent ?

Merci

**Comment by alexAubin** [comment]
Salut,

malheureusement je n'ai pas trop maintenu cette app et elle n'est pas très bien intégrée (c.f. le LDAP). (Mais pour d'autres projets je vais peut-être retravailler dessus dans les jours qui viennent)

Néanmoins cela m'étonne qu'elle ne s'installe pas bien car elle est relativement simple. Est-ce que tu peux relancer l'install en ligne de commande avec `--verbose --debug` pour avoir plus de détails ?

**Comment by ljoets** [comment]
Voilà ce que ça donne : http://paste.alacon.org/43671

**Comment by Jibec** [comment]
merci pour le ticket, je me permets de le clore, cela évoluera prochainement
